### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by luizcarlosfx** [uhhhci/Touchy#1]
How do I recompile the source code? From what I see you're using some source files that are not included. Is there a place where I can get them?

These are the files:
#include "HD/hd.h" //part of 3DS OpenHaptics ( how do i get 3ds open haptics source?)
#include <HDU/hduVector.h>
#include <HDU/hduError.h>

**Comment by yingkitcham** [comment]
https://3dssupport.microsoftcrmportals.com/knowledgebase/article/KA-03283/en-us

You are required to install OpenHaptics SDK before you compile the source code.

**Comment by joobei** [comment]
@luizcarlosfx we're not allowed to distribute these files so you must download the openhaptics Sdk. Please refer to the "Build Requirements" in the readme. Let me know if you need anymore help.
